[package]
name = "eappx"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.9.3"
binrw = "0.15.2"
flate2 = { version = "1.1.10", features = ["zlib-ng"] }
hex = "0.4.3"
uuid = "1.27.0"
sha2 = "0.11.0"
xmlserde = "0.14.0"
xmlserde_derives = "0.14.0"
xts-mode = { version = "0.6.0" }
base64ct = { version = "1.8.3", features = ["std"] }
log = "0.4.34"
thiserror = "2.0.21"

[workspace]
members = [
    "makeappx",
]
